// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:csv/csv.dart';

void main() {
  var csv = new CsvCodec(eol: "\n");
  var data = csv.decode(new File("data.csv").readAsStringSync());

  // Remove comments and empty lines.
  data.removeWhere((row) => row.length < 3);

  var file = new File("lib/src/generated.dart").openSync(mode: FileMode.WRITE);
  file.writeStringSync("""
    // Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
    // for details. All rights reserved. Use of this source code is governed by a
    // BSD-style license that can be found in the LICENSE file.

    // Don't modify this file by hand! It's generated by tool/generate.dart.

    /// Whether the symbol getters return plain ASCII, as opposed to Unicode
    /// characters or sequences.
    ///
    /// Defaults to `false`.
    bool get ascii => _ascii;
    var _ascii = false;
    set ascii(bool value) {
      _ascii = value;
      if (value) {
  """);

  for (var symbol in data) {
    file.writeStringSync("_${symbol[0]} = ${_quote(symbol[2])};");
  }

  file.writeStringSync("} else {");

  for (var symbol in data) {
    file.writeStringSync("_${symbol[0]} = ${_quote(symbol[1])};");
  }

  file.writeStringSync("}}");

  for (var symbol in data) {
    for (var line in symbol[3].split("\n")) {
      file.writeStringSync("/// $line\n");
    }

    file.writeStringSync("""
      ///
      /// If [ascii] is `false`, this is "${symbol[1]}". If it's `true`, this is
      /// "${symbol[2]}" instead.
      String get ${symbol[0]} => _${symbol[0]};
      var _${symbol[0]} = ${_quote(symbol[1])};
    """);
  }

  var result = Process.runSync(
      "pub", ["run", "dart_style:format", "-w", "lib/src/generated.dart"]);
  print(result.stderr);
  exit(result.exitCode);
}

String _quote(String input) => input.contains('"') ? "'$input'" : '"$input"';
